### ISSUE TITLE
Footer API

### ISSUE THREAD

**Issue by svbeon** [ShailenNaidoo/hydrogen#45]
In the docs the header api is commonly used to insert script tags, this is not great, script tags should come last on the page

One working solution is of course to just write script tags into the layout or page template, but an alternative would be to have a footer api, which is exactly the same as the header api, which you can place at the end of your page instead. This would be more in line with the usage in the docs

**Comment by ShailenNaidoo** [comment]
@svbeon Thanks for the suggestion! :)

In the docs for the Head API, you will see that most of the examples are for meta tags, not script tags https://hydrogenjs.org/docs/working-with-meta-data/

Also if you have required scripts like frameworks, analytics and etc those usually go in the head as well, the whole point of the Head API is to provide a lot of flexibility in how you compose metadata for SEO, It's up to you on how you use it. I don't see how the proposed Footer API would help as what you are describing can be easily solved by using the `default` layout or any layout template.

Also, check the Config API for the using the Global Head API https://hydrogenjs.org/docs/hydrogen-config/

Thanks for your first issue! Love the proposal, looking to see more ;)

**Comment by ShailenNaidoo** [comment]
No update, closing issue :)
